version: '3.7'
services:
  db:
    image: mysql:8.0
    container_name: magento_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - magento

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: magento_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - magento

  redis:
    image: redis:6.0-alpine
    container_name: magento_redis
    ports:
      - '6379:6379'
    networks:
      - magento

  php:
    build:
      context: ./docker/php
    container_name: magento_php
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - db
      - elasticsearch
      - redis
    networks:
      - magento

  nginx:
    image: nginx:1.19-alpine
    container_name: magento_nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - magento

  adminer:
    image: adminer
    container_name: magento_adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - magento

volumes:
  db_data:

networks:
  magento:
    driver: bridge
